name = "BinarySTSPackage"
uuid = "7852d2a1-850e-41f4-8ee9-04eb43b0ac3d"
authors = ["l.kampoli <l.kampoli@spbu.ru> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
